blog/urls.py
from django.urls import path
from .views import BlogDetailView
from .apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('blog_details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('message.urls', namespace='message')),
    path('user/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.views import RegisterView, CodeView, LoginView, UserUpdate, UserTemplateView, new_password, \
    PasswordsChangeView
from users.apps import UsersConfig
from . import views

app_name = UsersConfig.name

urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.LogoutUser, name='logout'),
    path('code/', CodeView.as_view(), name='code'),
    path('profile/', UserUpdate.as_view(), name='profile'),
    path('template/', cache_page(60)(UserTemplateView.as_view()), name='template'),
    path('template/newpassword', new_password, name='new_password'),
    path('user_password/', PasswordsChangeView.as_view(), name='user_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(verbose_name='Почта', unique=True)
    avatar = models.ImageField(upload_to='user/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=25, verbose_name='Номер телефона', **NULLABLE)
    surname = models.CharField(max_length=150, verbose_name='Отчество', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Активность')
    code = models.CharField(max_length=15, verbose_name='код', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from users.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms


class UserForm(UserCreationForm):
    password1 = forms.CharField(label='Пароль1', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пороля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    avatar = forms.ImageField(label='avatar', widget=forms.FileInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('email', 'avatar', 'password1', 'password2')


class PasswordChangingForm(PasswordChangeForm):
    pass


class UserFormUpdate(UserChangeForm):
    first_name = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-input'}))
    last_name = forms.CharField(label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-input'}))
    surname = forms.CharField(label='Отчество', widget=forms.TextInput(attrs={'class': 'form-input'}))
    avatar = forms.ImageField(label='avatar', widget=forms.FileInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'surname', 'avatar')

    def __init__(self, *args, **kwargs):
        super(UserFormUpdate, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.conf import settings
from django.contrib.auth import logout
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, View, UpdateView, TemplateView
from users.models import User
from users.forms import UserForm, UserFormUpdate, PasswordChangingForm
from users.services import new_pass, generation


class UserTemplateView(TemplateView):
    template_name = 'users/templates.html'


def LogoutUser(request):
    logout(request)

    return redirect('message:home')


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class RegisterView(CreateView):
    model = User
    template_name = 'users/register.html'
    form_class = UserForm
    success_url = reverse_lazy('users:code')

    def form_valid(self, form):
        password = generation()
        new_user = form.save(commit=False)
        new_user.code = password
        new_user.save()
        send_mail(
            subject='Подтверждение регистрации',
            message=f' Введите код: {new_user.code}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )

        return super().form_valid(form)


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/user_password.html'


class CodeView(View):
    model = User
    template_name = 'users/code.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        code = request.POST.get('code')
        user = User.objects.filter(code=code).first()

        if user is not None and user.code == code:
            user.is_active = True
            user.save()
            return redirect('users:login')


class UserUpdate(UpdateView):
    model = User
    template_name = 'users/update_profile.html'
    form_class = UserFormUpdate
    success_url = reverse_lazy('message:home')

    def get_object(self, queryset=None):
        return self.request.user


def new_password(request):
    a = new_pass(request)
    return a

users/templates/users/code.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Верификация</h1>
            <p class="fs-5 text-body-secondary">Введите код, который пришел на почту</p>
        </div>
    </header>
{% endblock %}
{% block body %}
    <div class="container py-5">
        <div class="row min-vh-50 justify-content-center align-items-center">
            <div class="col-md-6 col-lg-4">
                <div class="card shadow">
                    <div class="card-body">
                        <h4 class="card-title text-center mb-4 mt-1">Введите ваш код</h4>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="input-group">
                                    <input name="code" class="form-control" placeholder="Код подтверждения" type="text"
                                           required>
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-secondary btn-block m-2">Подтвердить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Вход</h1>
            <p class="fs-5 text-body-secondary">Введите почту и пароль</p>
        </div>
    </header>
{% endblock %}
{% block body %}

    <style>

        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }


        .form-box {
            width: 100%;
            max-width: 400px;
            padding: 20px;
            margin: auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #f8f8f8;
            border-radius: 8px;
        }


        .form-error {
            color: red;
            font-size: 0.9em;
            height: 30px;
        }


        .form-label {
            display: block; /* Метки блочного типа для лучшего контроля отступов */
            margin-bottom: 0.5em;
        }


        input[type="text"],
        input[type="password"],
        .button {
            width: 100%;
            padding: 10px;
            margin-bottom: 1em;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        /* Стилизация кнопки */
        button {
            background-color: #343a40;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
        }

        button:hover {
            background-color: #495057; /* Потемнее при наведении */
        }

    </style>

    <div class="form-container">
        <form class="form-box" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>

            {% for f in form %}
                <div class="fieldWrapper">
                    <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:</label>
                    {{ f }}
                    <div class="form-error">{{ f.errors }}</div>
                </div>
            {% endfor %}

            <button type="submit">Войти</button>
        </form>
    </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Регистрация</h1>
            <p class="fs-5 text-body-secondary">Введите данные для регистрации</p>
        </div>
    </header>
{% endblock %}

{% block body %}
    <style>
        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }

        .registration-form {
            margin: auto;
            padding: 2em;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            background: #ffffff;
        }

        .registration-form .form-error {
            color: #ff0000;
            margin-bottom: 1em;
        }

        .registration-form p {
            margin-bottom: 1em;
        }

        .registration-form input,
        .registration-form textarea,
        .registration-form select {
            width: 100%;
            padding: 0.5em;
            margin-bottom: 0.5em;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .registration-form button.btn-register {
            background-color: #007bff;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
        }

        .registration-form button.btn-register {
            background-color: #343a40;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
            transition: background-color 0.2s;
        }

        .registration-form button.btn-register:hover {
            background-color: #495057;
        }
    </style>


    <div class="form-container">
        <form method='post' enctype="multipart/form-data" class="registration-form">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {{ form.as_p }}
            <button type="submit" class="btn-register">Зарегистрироваться</button>


        </form>
    </div>
{% endblock %}

users/templates/users/templates.html
{% extends 'message/base.html' %}
{% load mediapath %}
{% block title %}
<div class="b-example-divider"></div>
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Личный кабинет</h1>
    </div>
</header>
{% endblock %}
{% block body %}
<div class="container">
    <div>
        <a class="w-40 btn btn-lg btn-success" href="{% url 'users:profile' %}">Редактитровать профиль</a>
    </div>
    {% if user.avatar %}
    <img src="{% mediapath user.avatar %}" width="20%" height="240" class="bd-placeholder-img">
    {% else %}
    <img src="{% mediapath 'user/face.jpeg' %}" width="20%" height="240" class="bd-placeholder-img">
    {% endif %}
    <h3 class="display-9 fw-normal text-body-emphasis">Имя: {{ user.first_name }}</h3>
    <h3 class="display-9 fw-normal text-body-emphasis">Фамилия: {{ user.last_name }}</h3>
    <h3 class="display-9 fw-normal text-body-emphasis">Отчество: {{ user.surname }}</h3>
    <a class="p-2 btn btn-outline-danger" href="{% url 'users:new_password' %}">Сгенирировать пароль</a>
    <a class="p-2 btn btn-outline-danger" href="{% url 'users:user_password' %}">Установить свой пароль</a>
</div>
{% endblock %}

users/templates/users/update_profile.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Профиль</h1>
            <p class="fs-5 text-body-secondary">Редактировать профиль</p>
        </div>
    </header>
{% endblock %}
{% block body %}
    <style>
        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }

        .registration-form {
            margin: auto;
            padding: 2em;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            background: #ffffff;
        }

        .registration-form .form-error {
            color: #ff0000;
            margin-bottom: 1em;
        }

        .registration-form p {
            margin-bottom: 1em;
        }

        .registration-form input,
        .registration-form textarea,
        .registration-form select {
            width: 100%;
            padding: 0.5em;
            margin-bottom: 0.5em;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .registration-form button.btn-register {
            background-color: #007bff;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
        }

        .registration-form button.btn-register {
            background-color: #343a40;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
            transition: background-color 0.2s;
        }

        .registration-form button.btn-register:hover {
            background-color: #495057;
        }
    </style>


    <div class="form-container">
        <form method='post' enctype="multipart/form-data" class="registration-form">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {{ form.as_p }}
            <button type="submit" class="btn-register">Изменить</button>
        </form>
    </div>
{% endblock %}

users/templates/users/user_password.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Вход</h1>
            <p class="fs-5 text-body-secondary">Введите почту и пароль</p>
        </div>
    </header>
{% endblock %}
{% block body %}

    <style>

        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }


        .form-box {
            width: 100%;
            max-width: 400px;
            padding: 20px;
            margin: auto;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #f8f8f8;
            border-radius: 8px;
        }


        .form-error {
            color: red;
            font-size: 0.9em;
            height: 30px;
        }


        .form-label {
            display: block; /* Метки блочного типа для лучшего контроля отступов */
            margin-bottom: 0.5em;
        }


        input[type="text"],
        input[type="password"],
        .button {
            width: 100%;
            padding: 10px;
            margin-bottom: 1em;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        /* Стилизация кнопки */
        button {
            background-color: #343a40;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
        }

        button:hover {
            background-color: #495057; /* Потемнее при наведении */
        }

    </style>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header">
                        <h4>Change Password</h4>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Update Password</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}