blog/urls.py
from django.urls import path
from .views import BlogDetailView
from .apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('blog_details/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('message.urls', namespace='message')),
    path('user/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views
from message.apps import MessageConfig
from .views import ContactView, HomeListView

app_name = MessageConfig.name
urlpatterns = [
    path('', cache_page(60)(HomeListView.as_view()), name='home'),
    path('contact/', cache_page(60)(ContactView.as_view()), name='contact'),
    path('client_create/', views.ClientCreateView.as_view(), name='client_create'),
    path('update/<int:pk>', views.ClientUpdateView.as_view(), name='update_client'),
    path('list/', views.ClientListView.as_view(), name='client_list'),
    path('delete/<int:pk>/detail/', views.ClientDeleteView.as_view(), name='delete'),
    path('mailings_list/', views.MailingsListView.as_view(), name='mailings_list'),
    path('mailings_create/', views.MailingsCreateView.as_view(), name='mailings_create'),
    path('update_mailings/<int:pk>/detail/', views.MailingsUpdateView.as_view(), name='update_mailings'),
    path('delete_mailings/<int:pk>/detail/', views.MailingsDeleteView.as_view(), name='delete_mailings'),
    path('Message_list/', views.MessageListView.as_view(), name='message_list'),
    path('message_create/', views.MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/detail/', views.MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/detail/', views.MessageDeleteView.as_view(), name='message_delete'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.views import RegisterView, CodeView, LoginView, UserUpdate, UserTemplateView, new_password, \
    PasswordsChangeView
from users.apps import UsersConfig
from . import views

app_name = UsersConfig.name

urlpatterns = [
    path('', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', views.LogoutUser, name='logout'),
    path('code/', CodeView.as_view(), name='code'),
    path('profile/', UserUpdate.as_view(), name='profile'),
    path('template/', cache_page(60)(UserTemplateView.as_view()), name='template'),
    path('template/newpassword', new_password, name='new_password'),
    path('user_password/', PasswordsChangeView.as_view(), name='user_password'),
]

message/models.py
from django.db import models

from config import settings


class Client(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, verbose_name='Пользователь')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', blank=True, null=True)
    surname = models.CharField(max_length=150, verbose_name='Отчество', blank=True, null=True)
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', null=True, blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    name = models.CharField(max_length=150, verbose_name='тема письма')
    body = models.TextField(verbose_name='содержимое письма')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Mailings(models.Model):
    stat_mailings = [
        ('start', 'Запущена'),
        ('finish', 'Завершена'),
        ('created', 'Создана')
    ]

    period = [
        ('once_a_day', 'Раз в день'),
        ('once_a_week', 'Раз в неделю'),
        ('once_a_month', 'Раз в месяц')
    ]
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Письмо', blank=True, null=True)
    client = models.ManyToManyField(Client)
    state = models.CharField(max_length=10, choices=stat_mailings, default='start', verbose_name='Статус')
    periodicity = models.CharField(choices=period, default='once_a_day', verbose_name='Переодичность')
    date = models.DateTimeField(verbose_name='время рассылки', null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.state} {self.periodicity}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    permissions = [
        (
            'set_status',
            'Can change status'
        )
    ]


class Log(models.Model):
    stat_mailings = [
        ('start', 'Запущена'),
        ('finish', 'Завершена'),
    ]
    data = models.DateTimeField(verbose_name='дата', null=True, blank=True)
    state = models.CharField(max_length=10, choices=stat_mailings, default='start', verbose_name='статус')
    email_answer = models.BooleanField(default=False, verbose_name='ответ от почты')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE, verbose_name='пользователь')
    mailings = models.ForeignKey('Mailings', on_delete=models.CASCADE, verbose_name='рассылка', null=True, blank=True)

    def __str__(self):
        return f'Отправлено: {self.data} ' \
               f'Статус: {self.state}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

message/forms.py
from django import forms

from message.models import Client, Message, Mailings


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ('user',)


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        exclude = ('user', 'client')


class MailingsForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailings
        exclude = ('user',)
        # fields = '__all__'

        widgets = {
            'time': forms.TimeInput(
                attrs={'type': 'time', }
            ),
            'date': forms.DateInput(
                attrs={'type': 'date', }
            )
        }

message/views.py
from random import sample

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, View, UpdateView, ListView, DeleteView

from blog.models import Blog
from message.models import Client, Mailings, Message, Log
from message.forms import MailingsForm, ClientForm, MessageForm


class VerificationMixin:
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь создателем этого клиента")
        return self.object


class HomeListView(ListView):
    model = Blog
    template_name = 'message/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        newsletters = Mailings.objects.all()
        active_newsletters = Mailings.objects.filter(state='start')
        client = Client.objects.all()
        context['count'] = newsletters.count()
        context['client'] = client.count()
        context['active_newsletters'] = active_newsletters.count()
        all_blogs = Blog.objects.all()
        context['random_blogs'] = sample(list(all_blogs), min(3, all_blogs.count()))

        return context


class ContactView(View):
    template_name = 'message/kontact.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        if request.method == 'POST':
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            message = request.POST.get('message')
            print(name, phone, message)
        return render(request, self.template_name)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'message/client_create.html'
    success_url = reverse_lazy('message:client_list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'message/update_client.html'
    success_url = reverse_lazy('message:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь создателем этого клиента")
        return self.object

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'message/client_list.html'

    def get_queryset(self, **kwargs):
        if self.request.user.groups.filter().exists():
            return Client.objects.all()
        return Client.objects.filter(user=self.request.user)


class ClientDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Client
    template_name = 'message/delete_client.html'
    success_url = reverse_lazy('message:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь создателем этого клиента")
        return self.object

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MailingsCreateView(LoginRequiredMixin, CreateView):
    """Создание рассылки"""
    model = Mailings
    form_class = MailingsForm
    success_url = reverse_lazy('message:mailings_list')

    def form_valid(self, form):
        """Добавление пользователя к рассылке"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingsListView(LoginRequiredMixin, ListView):
    """Просмотр списка рассылок"""
    model = Mailings
    form_class = MailingsForm

    def get_queryset(self):
        """Вывод рассылок пользователя либо всех рассылок для модератора"""
        if self.request.user.has_perm('message.view_mailings'):
            return super().get_queryset()
        return super().get_queryset().filter(user=self.request.user)


class MailingsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """Редактирование рассылки"""
    model = Mailings
    form_class = MailingsForm
    success_url = reverse_lazy('message:mailings_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MailingsDeleteView(LoginRequiredMixin,  UserPassesTestMixin, DeleteView):
    """Удаление рассылки"""
    model = Mailings
    success_url = reverse_lazy('message:mailings_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    template_name = 'message/message_list.html'

    def get_queryset(self):
        """Вывод сообщений пользователя"""
        return super().get_queryset().filter(user=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    template_name = 'message/create_message.html'
    success_url = reverse_lazy('message:message_list')

    def form_valid(self, form):
        """Добавление пользователя к сообщению"""
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Message
    form_class = MessageForm
    template_name = 'message/update_message.html'
    success_url = reverse_lazy('message:message_list')

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()


class MessageDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('message:message_list')
    template_name = 'message/delete_message.html'

    def test_func(self):
        user = self.request.user
        if user == self.get_object().user:
            return True
        return self.handle_no_permission()

message/templates/message/base.html
<!doctype html>
{% load static %}
{% load mediapath %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>Сервис управления рассылками</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div >
      <h1 class="display-6 fw-normal text-body-emphasis text-center">Сервис управления рассылками</h1>
      <h6 class="text-center">
            {% if user.is_authenticated %}
        <strong>Пользователь: {{ user.first_name }}\({{ user.email }})</strong>
        {% endif %}
          </h6>
</div>

<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="ms-5">
        {% if user.is_authenticated %}
        <a class="p-1 btn btn-outline-warning" href="/">Главная</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'message:client_list' %}">Клиенты</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'message:mailings_list' %}">Рассылки</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'message:message_list' %}">Сообщения</a>
        <a class="p-1 btn btn-outline-info" href="{% url 'users:template' %}">Кабинет</a>
        <a class="p-1 btn btn-outline-danger" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
        <a class="p-1 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-1 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
        <a class="p-1 btn btn-outline-primary" href="{% url 'message:contact' %}">Контакты</a>
        {% if user.is_superuser or user.is_staff %}
        <a class="p-1 btn btn-outline-info" href="/admin">Админка</a>
        {% endif %}
    </nav>
</div>
<div >
    <h2 class="display-6 text-center">{{ title|title }}</h2>
</div>
<div>
    {% block title %}
    {% endblock %}

    {% block body %}
    {% endblock %}
</div>
<div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                курсовая на Django фреймворк
                <small class="d-block mb-3 text-muted">&copy;{% now "Y" %}</small>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
</body>
</html>

message/templates/message/client_create.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Добавление клиента</h1>

        </div>
    </header>
{% endblock %}
{% block body %}
    <style>
        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 70vh;
        }

        .registration-form {
            width: 100%;
            max-width: 500px;
            margin: auto;
            padding: 2em;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            background: #ffffff;
        }

        .registration-form .form-error {
            color: #ff0000;
            margin-bottom: 1em;
        }

        .registration-form p {
            margin-bottom: 1em;
        }

        .registration-form input,
        .registration-form textarea,
        .registration-form select {
            width: 100%;
            padding: 0.5em;
            margin-bottom: 0.5em;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .registration-form button.btn-register {
            background-color: #007bff;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
        }

        .registration-form button.btn-register {
            background-color: #343a40;
            color: white;
            padding: 0.5em 1em;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1em;
            transition: background-color 0.2s;
        }

        .registration-form button.btn-register:hover {
            background-color: #495057;
        }

        @media (max-width: 768px) {
            .registration-form {
                padding: 1em; /* Уменьшаем отступы */
            }
        }

        /* Медиа-запросы для маленьких экранов, например, мобильных телефонов */
        @media (max-width: 576px) {
            .registration-form {
                padding: 0.5em; /* Ещё меньше отступов */
            }

            .registration-form input,
            .registration-form textarea,
            .registration-form select {
                padding: 0.25em; /* Уменьшаем отступы внутри полей ввода */
            }

            .registration-form button.btn-register {
                padding: 0.25em 0.5em; /* Уменьшаем отступы кнопки */
            }
        }
    </style>


    <div class="form-container">
        <form method='post' enctype="multipart/form-data" class="registration-form">
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {{ form.as_p }}
            <button type="submit" class="btn-register">Сохранить</button>


        </form>
{% endblock %}

message/templates/message/client_list.html
{% extends 'message/base.html' %}
{% block title %}
<div class="b-example-divider"></div>

<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Список клиентов</h1>
        </div>
    </header>
    {% endblock %}

    {% block body %}
    <div class="row text-start">
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for object in object_list %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <p class="card-text">
                                    имя: {{ object.first_name }}<br>
                                    фамилия: {{ object.last_name }}<br>
                                    отчество: {{ object.surname }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <div class="card-body">
                                            <p class="card-text">{{ object.email }}</p>
                                            <a type="button" class="btn btn-sm btn-outline-secondary"
                                               href="{% url 'message:update_client' object.pk %}">Редактировать</a>
                                            <a type="button" class="btn btn-sm btn-outline-danger"
                                               href="{% url 'message:delete' object.pk %}">Удалить</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <a class="m-2 p-2 btn btn-outline-primary" href="{% url 'message:client_create' %}">
                    Добавление клиента</a>
            </div>
        </div>
    </div>
    {% endblock %}
</div>

message/templates/message/delete_client.html
{% extends 'message/base.html' %}
{% block title %}
<div class="b-example-divider"></div>

<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление клиента</h1>
        </div>
    </header>

    {% endblock %}
    {% block body %}

    <div class="form-container">
        <form method='post'>
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {{ form.as_p }}
            <h3>Вы действительно хотите удалить клиента?</h3>
            <button type="submit" class="btn btn-danger">Да</button>
            <a href="{% url 'message:client_list' %}" class="btn btn-success">Нет</a>
        </form>
    </div>
</div>
{% endblock %}

message/templates/message/delete_mailings.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление рассылки</h1>
        </div>
    </header>
{% endblock %}
{% block body %}


    <div class="form-container">
        <form method='post'>
            {% csrf_token %}
            <div class="form-error">{{ form.non_field_errors }}</div>
            {{ form.as_p }}
            <h3>Вы действительно хотите удалить клиента?</h3>
            <button type="submit" class="btn btn-danger">Да</button>
            <button type="button" href="{% url 'message:client_list' %}" class="btn btn-success">Нет</button>


        </form>
{% endblock %}

message/templates/message/index.html
{% extends 'message/base.html' %}
{% load static %}
{% load mediapath %}

{% block body %}
<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Главная страница</h1>
    </div>
</header>
<main>
    <div class="row row-cols-1 row-cols-md-3 mb-6 text-center">
        <div class="col-md-12">
            <div class="card mb-4 rounded-6 shadow-sm">
                <div class="card-header py-1">
                    <h4 class="my-0 fw-normal">Статистика рассылок</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-1 mb-3">
                        <li>Количество рассылок всего: {{ count }}</li>
                        <li>Количество активных рассылок: {{ active_newsletters }}</li>
                        <li>Количество уникальных клиентов для рассылок: {{ client }}</li>
                    </ul>
                </div>
            </div>
            <div class="card mb-4 rounded-6 shadow-sm">
                <div class="card-header py-1">
                    <h4 class="my-0 fw-normal">Три случайные статьи из блога</h4>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="row mb-2">
            {% for object in random_blogs %}
            <div class="col-md-4 mb-4">
                <div class="row g-0 border rounded overflow-hidden flex-md-row shadow-sm h-md-250 position-relative">
                    <div class="col-auto d-none d-lg-block">
                        {% if object.photo %}
                        <img src="{{ object.photo.url }}" alt="Blog Image" width="200" height="250">
                        {% else %}
                        <svg class="bd-placeholder-img" width="200" height="250" xmlns="" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                        </svg>
                        {% endif %}
                    </div>
                    <div class="col p-4 d-flex flex-column position-static">
                        <h3 class="mb-0">{{ object.title }}</h3>
                        <div class="mb-1 text-body-secondary">{{ object.date }}</div>
                        <p class="card-text mb-auto">{{ object.body|slice:":150" }}</p>
                        Просмотры: {{ object.count_views }}
                    </div>
                    <div>
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'blog:blog_detail' object.pk %}">Подробнее</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

message/templates/message/mailings_list.html
{% extends 'message/base.html' %}
{% block title %}
<div class="b-example-divider"></div>
<div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Список рассылок</h1>
        </div>
    </header>
    {% endblock %}
    {% block body %}
    <div class="row text-start">
        <div class="album py-5 bg-body-tertiary">
            <div class="container">
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for object in object_list %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <div class="card-body">
                                <p class="card-text">клиенты:
                                    {% for client in object.client.all %}
                                    {{client}},
                                    {% endfor %}
                                    <br>периодичность: {{ object.periodicity }} <br>создатель: {{ object.user }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <div class="card-body">
                                            <p class="card-text">Тема: {{ object.message }} </p>
                                            <p class="card-text">Дата: {{ object.date }} </p>
                                            <p class="card-text">Статус: {{ object.state }} </p>
                                            <a type="button" class="btn btn-sm btn-outline-secondary"
                                               href="{% url 'message:update_mailings' object.pk %}">Редактировать</a>
                                            <a type="button" class="btn btn-sm btn-outline-danger"
                                               href="{% url 'message:delete_mailings' object.pk %}">Удалить</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <a class="m-2 p-2 btn btn-outline-primary" href="{% url 'message:mailings_create' %}">Добавить
                    рассылку</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

message/templates/message/message_list.html
{% extends 'message/base.html' %}
{% block title %}
    <div class="b-example-divider"></div>

    <div class="container">
    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Список сообщений</h1>
        </div>
    </header>
{% endblock %}
{% block body %}

    <div class="row text-start">

        <div class="album py-5 bg-body-tertiary">

            <div class="container">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for object in object_list %}
                        <div class="col">

                            <div class="card shadow-sm">
                                <div class="card-body">
                                    <p class="card-text">{{ object.state }} {{ object.periodicity }} {{ object.client }} </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <div class="card-body">
                                                <p class="card-text">Наименование: {{ object.name|slice:15 }} </p>
                                                <p class="card-text">Тело: {{ object.body|slice:15 }} </p>

                                                <a type="button" class="btn btn-sm btn-outline-secondary"
                                                   href="{% url 'message:message_update' object.pk %}">Редактировать</a>
                                                <a type="button" class="btn btn-sm btn-outline-danger"
                                                   href="{% url 'message:message_delete' object.pk %}">Удалить</a>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    {% endfor %}
                </div>
                <a class="m-2 p-2 btn btn-outline-primary" href="{% url 'message:message_create' %}">Добавление
                    письма</a>
            </div>
        </div>

{% endblock %}